var model = [{"CoffeeName":"'Lavazza Caffe Espresso'  ","BYN":39.8,"USD":20.7,"EUR":19.0},
                    {"CoffeeName":"'Lavazza Gran Crema Espresso'  ","BYN":42.8,"USD":22.3,"EUR":20.4},
                    {"CoffeeName":"'Lavazza Qualita Oro'  ","BYN":38.9,"USD":20.2,"EUR":18.5},
                    {"CoffeeName":"'Lavazza Qualita Rossa'  ","BYN":35.1,"USD":18.3,"EUR":16.7},
                    {"CoffeeName":"'Lavazza Qualita Oro'  ","BYN":10.4,"USD":5.4,"EUR":5.0},
                    {"CoffeeName":"'Lavazza Caffe Espresso'  ","BYN":21.8,"USD":11.4,"EUR":10.4},
                    {"CoffeeName":"'Жокей Классический'  ","BYN":8.9,"USD":4.6,"EUR":4.2},
                    {"CoffeeName":"'Жокей По-Восточному'  ","BYN":8.3,"USD":4.3,"EUR":4.0},
                    {"CoffeeName":"Lavazza Crema e Gusto'  ","BYN":12.1,"USD":6.3,"EUR":5.8},
                    {"CoffeeName":"Якобс Монарх  ","BYN":5.0,"USD":2.6,"EUR":2.4},
                    {"CoffeeName":"Dallmayr Prodomo'  ","BYN":11.4,"USD":5.9,"EUR":5.4},
                    {"CoffeeName":"Dallmayr Sonderklasse'  ","BYN":11.9,"USD":6.2,"EUR":5.6},
                    {"CoffeeName":"JARDIN All Day Long  ","BYN":6.4,"USD":3.3,"EUR":3.1},
                    {"CoffeeName":"Жокей Классический'  ","BYN":4.1,"USD":2.1,"EUR":2.0},
                    {"CoffeeName":"Жокей По-восточному'  ","BYN":4.2,"USD":2.2,"EUR":2.0},
                    {"CoffeeName":"Lavazza Crema e Gusto'  ","BYN":10.9,"USD":5.7,"EUR":5.2},
                    {"CoffeeName":"Lavazza Espresso'  ","BYN":11.4,"USD":5.9,"EUR":5.4},
                    {"CoffeeName":"Lavazza Mattino'  ","BYN":6.7,"USD":3.5,"EUR":3.2},
                    {"CoffeeName":"Lavazza Qualita Oro'  ","BYN":14.6,"USD":7.6,"EUR":7.0},
                    {"CoffeeName":"Lavazza Qualita Rossa'  ","BYN":12.3,"USD":6.4,"EUR":5.9},
                    {"CoffeeName":"Tchibo' Exclusive  ","BYN":8.5,"USD":4.4,"EUR":4.1},
                    {"CoffeeName":"растворимый 'JARDIN Kenya Kilimanjaro', 95 гр  ","BYN":6.7,"USD":3.5,"EUR":3.2},
                    {"CoffeeName":"растворимый Якобс Кронат Голд 95 гр. ст.банка  ","BYN":5.6,"USD":2.9,"EUR":2.7}]